//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiftlikOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stok
    {
        public int StokID { get; set; }
        public int StokTurId { get; set; }
        public decimal Miktar { get; set; }
        public System.DateTime StokGirisTarihi { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        public virtual StokTur StokTur { get; set; }
    }
}
