//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiftlikOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class vHayvan
    {
        public int HayvanID { get; set; }
        public string KupeNo { get; set; }
        public int CinsId { get; set; }
        public string CinsAd { get; set; }
        public decimal Agirlik { get; set; }
        public System.DateTime OlcumTarihi { get; set; }
    }
}
