//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiftlikOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSutTakip
    {
        public int SutHareketId { get; set; }
        public int HayvanId { get; set; }
        public string KupeNo { get; set; }
        public decimal Miktar { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    }
}
